<?php

/**
 * @file
 * Contains store_locator.module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\store_locator\StoreLocatorStorage;

/**
 * Implements hook_theme().
 */
function store_locator_theme($existing, $type, $theme, $path) {
  return array(
    'location_data' => array('variables' => array('location_data_var' => NULL)),
  );
}

/**
 * Custom preprocess to handle the item list and map infowindow.
 */
function template_preprocess_location_data(&$variables) {
  $variables['empty_data'] = '';
  $variables['page_title'] = \Drupal::config('store_locator.settings')->get('title');
  $list_data = StoreLocatorStorage::loadInfowindow('list');
  if (is_array($list_data['itemlist']) && !empty($list_data['itemlist'])) {
    $location_data = StoreLocatorStorage::loadInfowindow('infowindow');
    $search_field = $variables['location_data_var']['searchitem'];
    $variables['location_list'] = $list_data['itemlist'];
    $variables['searchField'] = $search_field;
    $variables['#attached']['drupalSettings']['store_locator']['data'] = $location_data['itemlist'];
    $variables['#attached']['drupalSettings']['store_locator']['markericon'] = $location_data['marker'];
    $variables['#attached']['library'][] = 'store_locator/store_locator.page';
  }
  else {
    $variables['empty_data'] = \Drupal::config('store_locator.settings')->get('message');
  }
}

/**
 * Append the Configured Google Map API key in script tag.
 *
 * Implements hook_page_attachments()
 */
function store_locator_page_attachments(array &$page) {
  $api_key = \Drupal::config('store_locator.settings')->get('api_key');
  $mapKey = array(
    '#tag' => 'script',
    '#attributes' => array(
      'src' => '//maps.googleapis.com/maps/api/js?key=' . $api_key,
    ),
  );
  $page['#attached']['html_head'][] = [$mapKey, 'mapKey'];
}

/**
 * Implements hook_entity_view_alter().
 */
function store_locator_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($build['#view_mode'] == 'full') {

    $lat = $build['name']['#object']->get('latitude')->value;
    $lng = $build['name']['#object']->get('longitude')->value;
    $lat_lng = array('lat' => (float) $lat, 'lng' => (float) $lng);
    $build['#attached']['drupalSettings']['store_locator']['latlng'] = $lat_lng;
    $build['mapi']['#markup'] = '<div id="map" class="bh-sl-map store-locator-page-view"></div>';
    $build['mapi']['#weight'] = 100;
    $build['#attached']['library'][] = 'store_locator/store_locator.page';
  }
}
